ss = ("De Python lessen worden gegeven voor Erik, Erwin en ook door Hidde")
op = ("Opdracht")
print(op, "1")
print(ss)
print(ss[37:41])
print(op, "2")
sd = ("SD vakken zijn Python, UXD, Frontend development en Backend development en nog veel meer ...")
print(sd)
print(sd[15:21])
print(sd[23:26])
print(sd[28:48])
print(sd[52:71])
print(op, "3")
sf = ("Wat is hier het laatste woord?")
print(sf)
print(sf[-6:])
print(op, "4")
sg = ("Het www is ontwikkeld vanaf 1989 door Tim Berners-Lee")
print(sg[4:8], sg[28:33])
